---
baseURL: "https://hugo-minimal.netlify.com/"
title: Hugo Starter
languageCode: "en-us"
metaDataFormat: yaml
pluralizeListTitles: false
enableRobotsTXT: true
paginate: 5 # Number of posts per page

permalinks:
  blog: /:section/:year/:month/:slug/
  products: /:section/:slug/

taxonomies:
  category: category
  tag: tags

outputs:
  home:
    - HTML
    - JSON
  section:
    - HTML
    - RSS
    - JSON
  page:
    - HTML
    - JSON

menu:
  main:
    - Name: "About"
      Weight: 1
      Identifier: "about"
      URL: "/about/"
    - Name: "Products"
      Weight: 2
      Identifier: "products"
      URL: "/products/"
    - Name: "Blog"
      Weight: 3
      Identifier: "blog"
      URL: "/blog/"
    - Name: "Contact Us"
      Weight: 4
      Identifier: "contact"
      URL: "/contact/"

params:
  Title: "Hugo Starter"
---
