---
baseURL: "https://hugo-minimal.netlify.com/"
title: Hugo Starter
languageCode: "en-us"
metaDataFormat: yaml
pluralizeListTitles: false
enableRobotsTXT: true
paginate: 5 # Number of posts per page

permalinks:
  blog: /:section/:year/:month/:slug/
  products: /:section/:slug/

taxonomies:
  category: category
  tag: tags

outputs:
  home:
    - HTML
    - JSON
  section:
    - HTML
    - RSS
    - JSON
  page:
    - HTML
    - JSON

menu:
  main:
    - Name: "About"
      Weight: 1
      Identifier: "about"
      URL: "/about/"
    - Name: "Products"
      Weight: 2
      Identifier: "products"
      URL: "/products/"
    - Name: "Blog"
      Weight: 3
      Identifier: "blog"
      URL: "/blog/"
    - Name: "Contact Us"
      Weight: 4
      Identifier: "contact"
      URL: "/contact/"

params:
  Title: "Hugo Starter"
  CopyrightHTML: "Copyright &#xA9; 2018 Grayscale Digital LLC"
  default_cta_heading: Try Us Out
  default_cta_desc: >
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec et lorem sed quam porta rhoncus. 
    Pellentesque porttitor nisi sit amet tortor tristique, nec euismod odio laoreet.
  default_cta_narrow_desc: Want some human contact?
  default_cta_narrow_text: Really, try contacting us
  navigation:
    social:
      - Name: "Reddit"
        Weight: 1
        Identifier: "reddit-alien"
        URL: "https://www.reddit.com/r/funny/"
      - Name: "Facebook"
        Weight: 2
        Identifier: "facebook-square"
        URL: "https://facebook.com"
      - Name: "Twitter"
        Weight: 3
        Identifier: "twitter"
        URL: "https://twitter.com/grayscale_digi"
      - Name: "GitHub"
        Weight: 4
        Identifier: "github"
        URL: "https://github.com/rebolyte"
---
