backend:
  name: git-gateway
  branch: master

media_folder: "static/images" # Media files will be stored in the repo under static/images
public_folder: "/images" # The src attribute for uploaded media will begin with /images

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home"
        file: "content/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Sections"
            name: "blocks"
            widget: "list"
            typeKey: "template"
            types:
              - label: "1 Up"
                name: "1up"
                widget: object
                fields:
                  - { label: "Heading", name: "heading", widget: "string" }
                  - { label: "Text", name: "content", widget: "markdown" }
              - label: "2 Up"
                name: "2up"
                widget: object
                fields:
                  - { label: "Heading", name: "heading", widget: "string" }
                  - { label: "Left Text", name: "left", widget: "markdown" }
                  - { label: "Right Text", name: "right", widget: "markdown" }
      - name: "about"
        label: "about"
        file: "content/about/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }          
          - { label: "Body", name: "body", widget: "markdown" }
      - name: "contact"
        label: "Contact"
        file: "content/contact/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "date" }
      - { label: "Slug", name: "slug", widget: "string", required: false }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Hero Type", name: "hero_type", widget: "select", options: ["image", "video"] }
      - { label: "Hero Image", name: "hero_src", widget: "image", default: "http://via.placeholder.com/500x280", required: false }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", allow_add: true, required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", required: false }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Weight", name: "weight", widget: "number" }
      - { label: "Splash Type", name: "splash_type", widget: "select", options: ["image", "video"] }
      - { label: "Splash Image", name: "splash_src", widget: "image", default: "http://via.placeholder.com/500x280" }
      - { label: "CTA Text", name: "cta_text", widget: "string" }
      - { label: "CTA URL", name: "cta_url", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
