backend:
  name: git-gateway
  branch: master

media_folder: "static/images" # Media files will be stored in the repo under static/images
public_folder: "/images" # The src attribute for uploaded media will begin with /images

default_block_list: &default_block_list
  - label: "1 Up"
    name: "1up"
    widget: object
    fields:
      - { label: "Heading", name: "heading", widget: "string" }
      - { label: "Text", name: "content", widget: "markdown" }
  - label: "1 Up Media"
    name: "1up-media"
    widget: object
    fields:
      - { label: "Heading", name: "heading", widget: "string" }
      - label: "Type"
        name: "content"
        widget: "select"
        options: ["image", "video"]
        default: "image"
      - { label: "Image", name: "src", widget: "image", default: "https://via.placeholder.com/500x280" }
  - label: "2 Up"
    name: "2up"
    widget: object
    fields:
      - { label: "Heading", name: "heading", widget: "string" }
      - { label: "Left Text", name: "left", widget: "markdown" }
      - { label: "Right Text", name: "right", widget: "markdown" }
  - label: "Accordion"
    name: "accordion"
    widget: "object"
    fields:
      - label: "Accordion Items"
        name: "accordion_items"
        widget: "list"
        create: true
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "markdown" }
  - label: "Action Feature"
    name: "action-feature"
    widget: object
    fields:
      - { label: "Heading", name: "heading", widget: "string" }
      - { label: "Content", name: "content", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image", default: "https://via.placeholder.com/500x280" }
      - label: "Image Position"
        name: "image_position"
        widget: "select"
        options: ["left", "right"]
      - { label: "Button Text", name: "button_text", widget: "string" }
      - { label: "Button URL", name: "button_url", widget: "string" }
      - { label: "Dark Background?", name: "bg_dark", widget: "boolean", default: false }
  - label: "Card Grid"
    name: "card-grid"
    widget: object
    fields:
      - { label: "Columns", name: "num_cols", widget: "number", valueType: int, default: 3, min: 1, max: 12 }
      - label: "Cards"
        name: "cards"
        widget: "list"
        create: true
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Button Text", name: "buttonText", widget: "string" }
          - { label: "Button URL", name: "buttonUrl", widget: "string" }
  - label: "Grid List"
    name: "grid-list"
    widget: object
    fields:
      - { label: "Columns", name: "num_cols", widget: "number", valueType: int, default: 4, min: 4, max: 8, step: 2 }
      - label: "Items"
        name: "grid_items"
        widget: "list"
        create: true
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
  - label: "Media Feature"
    name: "media-feature"
    widget: object
    fields:
      - { label: "Heading", name: "heading", widget: "string" }
      - { label: "Content", name: "content", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image", default: "https://via.placeholder.com/500x280" }
      - label: "Image Position"
        name: "image_position"
        widget: "select"
        options: ["left", "right"]
  - label: "Narrow CTA"
    name: "narrow-cta"
    widget: object
    fields:
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Link Text", name: "link_text", widget: "string" }
      - { label: "Link URL", name: "link_url", widget: "string" }

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home"
        file: "content/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown", required: false }
          - label: "Blocks"
            name: "blocks"
            widget: "list"
            typeKey: "template"
            types: *default_block_list
      - name: "about"
        label: "about"
        file: "content/about/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }          
          - { label: "Body", name: "body", widget: "markdown", required: false }
          - label: "Blocks"
            name: "blocks"
            widget: "list"
            typeKey: "template"
            types: *default_block_list
      - name: "contact"
        label: "Contact"
        file: "content/contact/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown", required: false }
          - label: "Blocks"
            name: "blocks"
            widget: "list"
            typeKey: "template"
            types: *default_block_list
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "date" }
      - { label: "Slug", name: "slug", widget: "string", required: false }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Hero Type", name: "hero_type", widget: "select", options: ["image", "video"] }
      - { label: "Hero Image", name: "hero_src", widget: "image", default: "https://via.placeholder.com/500x280", required: false }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", allow_add: true, required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", required: false }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Weight", name: "weight", widget: "number" }
      - { label: "Splash Type", name: "splash_type", widget: "select", options: ["image", "video"] }
      - { label: "Splash Image", name: "splash_src", widget: "image", default: "https://via.placeholder.com/500x280" }
      - { label: "CTA Text", name: "cta_text", widget: "string" }
      - { label: "CTA URL", name: "cta_url", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - label: "Blocks"
        name: "blocks"
        widget: "list"
        typeKey: "template"
        types: *default_block_list
  - name: "config"
    label: "Config"
    files:
      - label: "Site Config"
        name: "siteconfig"
        file: "/data/siteconfig.yaml"
        fields:
          - { label: "Copyright", name: "CopyrightHTML", widget: "string" }
          - { label: "Contact Phone", name: "contact_phone", widget: "string" }
          - { label: "Contact Email", name: "contact_email", widget: "string" }
          - { label: "Default CTA Heading", name: "default_cta_heading", widget: "string" }
          - { label: "Default CTA Description", name: "default_cta_desc", widget: "string" }
          - { label: "Default Narrow CTA Description", name: "default_cta_narrow_desc", widget: "string" }
          - { label: "Default Narrow CTA Text", name: "default_cta_narrow_text", widget: "string" }
          - label: "Navigation"
            name: "navigation"
            widget: "object"
            fields:
              - label: "Social"
                name: "social"
                widget: "list"
                create: true
                fields:
                  - { label: "Name", name: "Name", widget: "string" }
                  - { label: "Weight", name: "Weight", widget: "number" }
                  - { label: "Icon", name: "Identifier", widget: "string" }
                  - { label: "URL", name: "URL", widget: "string" }
